global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ecs-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'node-exporter'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: .*ecs.*
        action: keep

