nce
    Description: ID of the created EC2 instance
AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a t2.micro EC2 instance with SSH access

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c55b159cbfafe1f0  # (Example for Amazon Linux 2 in us-east-1)
      SecurityGroupIds:
        - !Ref EC2SecurityGroup

Outputs:
  InstanceId:
    Value: !Ref EC2Insta
