apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-yml
  name: nginx-yml
spec:
  containers:
  - image: nginx
    name: nginx-yml
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
